### ISSUE TITLE
Consider using proper html copyright symbol

### ISSUE THREAD

**Issue by sangjunp4rk** [carolynhaines/TeaCozy#2]
Just know of the existence of the html copyright sign, which is `&copy;` and other special characters. You can find all of special characters for html here https://www.ascii.cl/htmlcodes.htm

https://github.com/carolynhaines/TeaCozy/blob/master/index.html#L111

**Comment by carolynhaines** [comment]
I went back and forth with this, but ultimately left the copyright symbol out because the Codecademy example and redline didn't include it. I was trying to match the redlines exactly, and thought it was an odd choice too
