### ISSUE TITLE
Add mobile resizing

### ISSUE THREAD

**Issue by sangjunp4rk** [carolynhaines/TeaCozy#3]
In the future, try to incorporate mobile resizing. Though it may seem tedious, it is an incredibly important concept since screen sizes vary tremendously today and it’s important that you website looks exactly as you design it to. Check out this site for more information about it https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries

https://github.com/carolynhaines/TeaCozy/blob/master/resources/css/style.css#L1

**Comment by carolynhaines** [comment]
Yeah, I'm looking forward to the responsive design unit in this course. I haven't learned it yet, but once I get through that material I will certainly incorporate mobile sizing in my future projects. Thanks!
